LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := SemcExactCalculator
LOCAL_OVERRIDES_PACKAGES := Calculator ExactCalculator
APP_NAME := ExactCalculator
LOCAL_SRC_FILES := $(APP_NAME).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
